# Generated by Django 4.1.4 on 2022-12-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyden_user',
            name='hobby',
            field=models.CharField(default='', max_length=255),
        ),
    ]
