# Generated by Django 4.1.4 on 2022-12-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pyden_user_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_uuid', models.CharField(max_length=250)),
                ('trip_uuid', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
                ('booked_by_user_uuid', models.CharField(max_length=250)),
                ('booking_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=250)),
                ('currency_code', models.CharField(max_length=250)),
                ('transferred_trip_uuid', models.CharField(max_length=250)),
                ('updated_by', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
    ]
